name: Backend CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: pwd
      - run: ls -al
      - run: cd frontend
      - run: ls
      - run: npm i
      - run: npm run build --if-present
      - run: npm test