name: Backend CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: pwd
      - run: ls
      - run: npm i
      - run: npm run build --if-present
      - run: npm test
      - run: docker build -t victorgentle/reactjs-api .
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build -t victorgentle/reactjs-api .
      - name: Publish image to docker hub
      - run: docker push victorgentle/reactjs-app:latest:latest