name: Frontend CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: print working directory
      - run: pwd

      - name: list them
      - run: ls
      - run: cd frontend
      - run: ls

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm i
      - run: npm run build --if-present
      - run: npm test